import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer"
import Image from "next/image";
import Link from "next/link"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Mem's Handmade",
  description: "Generated by MeM",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <header className="w-full py-6 bg-background">
      <div className="container flex flex-col items-center justify-center gap-6">
        <div className="inline-flex items-center gap-2 text-2xl font-bold">
        
        <Image
          src="/memshandmade-com-logo.png" 
 
          alt="Memshandmade.com logo"
          width={400}
          height={76}
          className="object-cover w-full "
        />
      </div>
       


        
 
      </div>
    </header>

        {children}
        <Footer />
      </body>
    </html>
  );
}
